apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-no-privilege-escalation
  annotations:
    policies.kyverno.io/title: Require No Privilege Escalation
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Containers must explicitly disable privilege escalation.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-no-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Privilege escalation must be disabled."
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false