#workflow name
name: Secure CI

#trigger
on:
  push:
    branches:
       -main
  pull_request:
     branches:
       -main
#permissions-least privilege
permission:
   contents: read

jobs:
  secret-scan:
     name: Secret Scan - Gitleaks
     run-on: ubuntu-latest

   steps:
    - name: Checkout repository
      user: actions/checkout@v4
      with:
        fetch-depth: 0
#tells GitHub Actions to fetch the full Git history
# rather than only latest commit 
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
